databases:
  - name: development
    databaseName: development
    user: mino
    region: singapore

services:
  - type: web
    name: tactica-note
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgres://mino:nfDycRn0oWhfmzwFW2np9e7pUtPJPu95@dpg-cel26dhgp3jlcsmj5s30-a/development_91o9
        fromDatabase:
          name: development
          property: connectionString
      - key: c68203ae34cd00d0ab270cad77ff4b47
        sync: false
